from django.db import models
from django.utils import timezone


class EmailMessage(models.Model):
	message_id = models.CharField(max_length=255, blank=True, null=True)
	mail_from = models.CharField(max_length=255)
	mail_to = models.TextField(help_text='Comma-separated recipients')
	subject = models.CharField(max_length=1024, blank=True, null=True)
	headers = models.TextField(blank=True, null=True)
	body = models.TextField(blank=True, null=True)
	attachments = models.TextField(blank=True, null=True, help_text='JSON list or filenames')
	received_at = models.DateTimeField(default=timezone.now)
	# link to GeneratedAddress when applicable
	generated_address = models.ForeignKey('GeneratedAddress', null=True, blank=True, on_delete=models.SET_NULL, related_name='messages')

	def __str__(self) -> str:
		return f"{self.subject or '(no subject)'} from {self.mail_from}"



class GeneratedAddress(models.Model):
    """Record of addresses generated by the site so we can track usage/stats."""
    local_part = models.CharField(max_length=255, db_index=True)
    domain = models.CharField(max_length=255, default='mail.geniusgsm.com')
    created_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField(blank=True, null=True)
    source_ip = models.CharField(max_length=64, blank=True, null=True)
    user_agent = models.CharField(max_length=1024, blank=True, null=True)
    message_count = models.IntegerField(default=0)

    class Meta:
        unique_together = (('local_part', 'domain'),)

    def full_address(self):
        return f"{self.local_part}@{self.domain}"

    def __str__(self) -> str:
        return self.full_address()


class SiteSetting(models.Model):
    """Simple key/value store for site-level settings (logo, title, etc.).

    Example usage:
        SiteSetting.objects.create(key='logo_svg', value='<svg>...</svg>')
    """
    key = models.CharField(max_length=128, unique=True, db_index=True)
    value = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return f"{self.key}"
