# Generated by Django 5.2.10 on 2026-01-31 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_from', models.CharField(max_length=255)),
                ('mail_to', models.TextField(help_text='Comma-separated recipients')),
                ('subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, help_text='JSON list or filenames', null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
