# Generated by Django 5.2.10 on 2026-01-31 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailreceiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(default='mail.geniusgsm.com', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1024, null=True)),
                ('message_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('local_part', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='generated_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mailreceiver.generatedaddress'),
        ),
    ]
